// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {conversations} from '../models';
import {sessions} from '../models';

export function CancelRun(arg1:string):Promise<void>;

export function CreateConversation():Promise<conversations.Conversation>;

export function DeleteConversation(arg1:string):Promise<void>;

export function GetConversationMessages(arg1:string):Promise<Array<sessions.ChatMessage>>;

export function GetSetting(arg1:string):Promise<string>;

export function ListConversations():Promise<Array<conversations.Conversation>>;

export function SendMessage(arg1:string,arg2:string):Promise<void>;

export function SetSetting(arg1:string,arg2:string):Promise<void>;

export function SetWindowScale(arg1:number):Promise<void>;
