// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelRun(arg1) {
  return window['go']['app']['AppService']['CancelRun'](arg1);
}

export function CreateConversation() {
  return window['go']['app']['AppService']['CreateConversation']();
}

export function GetConversationMessages(arg1) {
  return window['go']['app']['AppService']['GetConversationMessages'](arg1);
}

export function ListConversations() {
  return window['go']['app']['AppService']['ListConversations']();
}

export function SendMessage(arg1, arg2) {
  return window['go']['app']['AppService']['SendMessage'](arg1, arg2);
}
